datadir: data
dendrogram_file: dendrogram.png
books:
- name: Cosmic Saboteur
  author: Frank M. Robinson
  link: "https://www.gutenberg.org/cache/epub/66540/pg66540.txt"
  txt_file: cosmic_saboteur.txt
  word_analysis_file: word_analysis_cosmic_saboteur.yaml
  sentence_analysis_file: sentence_analysis_cosmic_saboteur.yaml
  book_id: id_1
- name: The Killer
  author: J. T. Oliver
  link: "https://www.gutenberg.org/files/65770/65770-0.txt"
  txt_file: the_killer.txt
  word_analysis_file: word_analysis_the_killer.yaml
  sentence_analysis_file: sentence_analysis_the_killer.yaml
  book_id: id_2
- name: WISE MEN AND A MULE
  author: W. C. Tuttle
  link: "https://www.gutenberg.org/cache/epub/66823/pg66823.txt"
  txt_file: wise_men_and_a_mule.txt
  word_analysis_file: word_analysis_wise_men_and_a_mule.yaml
  sentence_analysis_file: sentence_analysis_wise_men_and_a_mule.yaml
  book_id: id_3
- name: The People of the Abyss
  author: Jack London
  link: https://www.gutenberg.org/files/1688/1688-0.txt
  txt_file: the_people_of_the_abyss.txt
  word_analysis_file: word_analysis_the_people_of_the_abyss.yaml
  sentence_analysis_file: sentence_analysis_the_people_of_the_abyss.yaml
  book_id: id_4

